### ISSUE TITLE
which ide you used for RTL8710

### ISSUE THREAD

**Issue by sarwadenj** [kissste/rtl8710_mp3_decoder#1]
Hi,
which ide you used for RTL8710.

**Comment by kissste** [comment]
I have not used any IDE. Any text editor will do the job, such as Notepad++ on Windows, vi and Geany on Linux.

**Comment by sarwadenj** [comment]
Thanks,
so how you made setup. Cause i'm not getting any better information about setup.
I would like to use text editor  for coding so please help me how to make set up. How i used their RTL8710 SDK and  how i will upload code in it.

Thanks for immediate reply.
